### ISSUE TITLE
[Could not find method] org.apache.xmlbeans.impl.values.TypeStore.add_element_user

### ISSUE THREAD

**Issue by Xoxow62** [andruhon/AndroidReadXLSX#3]
Hi ! I hope u've could help me , sorry for my bad english btw i'll try to do my best to explain to you my problem. I've create a new project with POI library , I use your library its allow me to dont have over +65K methods. So my problem is Eclipse look's like he doesn't found the method or library I need.

There is my LogCat : 

![8009b1e651a195578d75d8c0fe7079e8](https://cloud.githubusercontent.com/assets/15263453/12322097/6326dd44-bab2-11e5-86fa-9bb460adca23.png)

If you need more informations about coding i've done or logs ..
I'll respond as soon as possible . Thank you

**Comment by andruhon** [comment]
Hi! I think it is a known issue of creating a new spreadsheet. It happens due to nature of this hack, I indeed chopped many classes out of the jar in order to overtake the 56k method limits.

Please confirm that it is a creation of a new worksheet causing your problem.

If it is spreadsheet creation issue you can do the following workaround:
*Create a new blank xlsx file in beforehand on your computer and keep this file in your app's resources;
*Open this existing blank xlsx file instead of creating a new one;
*Save this file somewhere else (to keep the template itself unchanged) or send this file somewhere;

You can also drop support of android below version 5 and use not shrunk version of the POI.

**Comment by Xoxow62** [comment]
Hi , yes it is a creation of new worksheet , i'm using this method 

XSSFWorkbook wb = new XSSFWorkbook();

**Comment by andruhon** [comment]
Ok. I think you need to use workaround mentioned above. Do you really need android 4 support?

**Comment by Xoxow62** [comment]
I've found an alternative with Docx4J and its work , so i guess i'm leaving POI now. 
Thank you for responding quickly ! If I must reuse it later I will not hesitate to come to you.
Have a good day :)

**Comment by andruhon** [comment]
Do you mean something like this: https://github.com/plutext/docx4j/blob/master/src/samples/xlsx4j/org/xlsx4j/samples/CreateSimpleSpreadsheet.java

**Comment by Xoxow62** [comment]
No no , its about word sheet, with .doc or .docx not about xlsx sheet
